### ISSUE TITLE
add cell with overall accuracy

### ISSUE THREAD

**Issue by gfrogat** [Caleydo/malevo#154]
We still don't have a cell which shows an accuracy curve. 

We should add this as soon as possible.

![image](https://user-images.githubusercontent.com/5851088/39986814-2460c6ec-5763-11e8-980b-d0007b7572f9.png)

**Comment by NMO13** [comment]
I have added an overall accuracy cell to the confusion matrix.
I did not put it under the precision column since it makes the impression that it is related to the precision. Therefore I decided to put it between the FN/FP columns.
![image](https://user-images.githubusercontent.com/3988444/42044682-ea5e4e78-7af9-11e8-9b60-3580ec7631bc.png)

Please provide feedback.

**Comment by thinkh** [comment]
Done with PR #189.
